name: 'Run ansible-lint with reviewdog'
description: '🐶 Run ansible-lint with reviewdog on pull requests to improve code review experience.'
author: 'takezyou'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: | 
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
  ansiblelint_flags:
    description: 'flags and args of ansible-lint command. Default auto-detection mode' 
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'orange'
